recipe: default.v1
language: en
pipeline:
#- name: custom.cmd_gen_with_sys_prompt.CustomLLMCommandGenerator
- name: SingleStepLLMCommandGenerator
  llm:
    provider: openai
    model: gpt-4o-2024-11-20
    timeout: 7
    max_tokens: 256
    temperature: 0
    cache:
      no-cache: true
  prompt_template: prompt_templates/ah_new_dsl.jinja2

policies:
- name: FlowPolicy
assistant_id: 20240513-110741-taxonomic-iron
