recipe: default.v1
language: en
pipeline:
- name: SingleStepLLMCommandGenerator
  llm:
    provider: rasa
    model: rasa/cmd_gen_codellama_13b_calm_demo
    api_base: "https://tutorial-llm.rasa.ai"
    temperature: 0
  flow_retrieval:
    active: false
  prompt_template: prompt_templates/time_aware_prompt.jinja2

policies:
- name: FlowPolicy
assistant_id: 20240513-110741-taxonomic-iron
